services:
  mysql:
    image: mysql:8.0               # Use the latest MySQL image
    container_name: mysql_local       # Name the container for easy identification
    ports:
      - "3306:3306"                   # Map MySQL's default port
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword     # Root user password
      MYSQL_DATABASE: planify_dev            # Default database to be created
      MYSQL_USER: dev_user                   # Development user
      MYSQL_PASSWORD: dev_password           # Password for the development user
    volumes:
      - planify_mysql_data:/var/lib/mysql      # Persistent storage for data
    networks:
      - planify_network

volumes:
  planify_mysql_data:                         # Define a Docker volume for MySQL data persistence
    name: planify_mysql_data                  # Name the volume for easy identification

networks:
  planify_network:                    # Custom network for isolation
    driver: bridge
