USE planify_dev;
-- Drop all tables
DROP TABLE IF EXISTS Payments;
DROP TABLE IF EXISTS TenantSubscriptions;
DROP TABLE IF EXISTS Plans;
DROP TABLE IF EXISTS Comments;
DROP TABLE IF EXISTS UserProjects;
DROP TABLE IF EXISTS Tasks;
DROP TABLE IF EXISTS Projects;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS UsageTracking;
DROP TABLE IF EXISTS Tenants;